### ISSUE TITLE
Japanese names to romaji.

### ISSUE THREAD

**Issue by justjuust** [miurahr/pykakasi#105]
**Describe the bug**
Hi,

I am trying to translate Japanese names to Romaji. I used the code written under. As you can see I get the same output for hira, kana, hepburn, kunrei and passport.
Is there anything wrong with my text or code?

**To Reproduce**
```
import pykakasi
kks = pykakasi.kakasi()
text='ｿｳｿﾞｸﾆﾝ'
result = kks.convert(text)
print(result)


[{'orig': 'ｿｳｿﾞｸﾆﾝ', 'hira': 'ｿｳｿﾞｸﾆﾝ', 'kana': 'ｿｳｿﾞｸﾆﾝ', 'hepburn': 'ｿｳｿﾞｸﾆﾝ', 'kunrei': 'ｿｳｿﾞｸﾆﾝ', 'passport': 'ｿｳｿﾞｸﾆﾝ'}]
```

**Comment by miurahr** [comment]
Already discussed on #87 about super legacy half-width katakana characters.

**Comment by miurahr** [comment]
You can do
```
text='ｿｳｿﾞｸﾆﾝ'
kks = pykakasi.kakasi()
result = kks.convert(jaconv.h2z(text))
```

**Comment by justjuust** [comment]
Hi,

Thank you.
I used the following solution and it works:

```text = "ｿｳｿﾞｸﾆﾝ'"
kakasi = pykakasi.kakasi()
kakasi.setMode("K", "a")
conv = kakasi.getConverter()
result = conv.do(jaconv.h2z(text))
```

**Comment by miurahr** [comment]
Does #106 satisfy your requirement?
