### ISSUE TITLE
Both "こんやく" and "こにゃく" is translated into "konyaku"

### ISSUE THREAD

**Issue by shinbero** [miurahr/pykakasi#107]
**Describe the bug**
＊これはバグと呼んで良いのか迷いますが、気になったのでissueを起票させていただきます。（本issue内ではバグと呼ばさせていただきます）

違う日本語の単語が同一のローマ字に変換されてしまうバグです。
"こんやく", "こにゃく"がどちらも"konyaku"というローマ字に変換されてしまいます。

また、"こんにゃく"は"konnyaku"というローマ字に変換されますが、これを逆に(人間が)ひらがなに変換するとしたら"こんにゃく", "こんやく"という２つの選択肢があると思います。

pykakasiが目指すところとして、
「ローマ字への変換 」 =   「読みようによっては、元々のひらがなが推定出来る」というものであれば現在の仕様でも良いと思いましたが、
「ローマ字への変換 」 =   「元々のひらがなが一意に決定出来る」というものであれば現在の仕様はバグと呼べるのかなと思いました。

I'm not sure I should call this situation as a bug, but I created this issue to discuss.

The bug is, different two Japanese is translated into same rōmaji.
For example, "こんやく" and "こにゃく" is both  translated into "konyaku".
And also, "こんにゃく" is translated as "konnyaku", then this rōmaji can be translated not only "こんにゃく" but also "こんやく" by human.
 

If pykakasi concept is ` 'Translating into rōmaji' = 'In some way, human can infer original Japanese' `, this behavior should not be called as bug, but specification.
But if pykakasi concept is ` 'Translating into rōmaji' = 'Human always can get original Japanese' `, this behavior should be called as bug, I think.

**To Reproduce**
Run following code with python3 in interactive mode.
(Of corse this also happens with script mode.)

```
>>> import pykakasi
>>> kks = pykakasi.kakasi()
>>>
>>> kks.convert("こんやく")
[{'orig': 'こんやく', 'hira': 'こんやく', 'kana': 'コンヤク', 'hepburn': 'konyaku', 'kunrei': 'konyaku', 'passport': 'konyaku'}]
>>>
>>> kks.convert("こにゃく")
[{'orig': 'こにゃく', 'hira': 'こにゃく', 'kana': 'コニャク', 'hepburn': 'konyaku', 'kunrei': 'konyaku', 'passport': 'konyaku'}]
>>>
>>> kks.convert("こんにゃく")
[{'orig': 'こんにゃく', 'hira': 'こんにゃく', 'kana': 'コンニャク', 'hepburn': 'konnyaku', 'kunrei': 'konnyaku', 'passport': 'konnyaku'}]
```

**Expected behavior**
` こにゃく should be "konyaku" `
` こんやく should be "konnyaku" `
` こんにゃく should be "konnnyaku" `

**Environment (please complete the following information):**
 - OS: [ docker alpine3.11 OS on 'macOS Big Sur' host ]
 - Python(CPython) [3.8.3]
 - pykakasi version: pykakasi==2.0.1 via pip install

**Comment for fixing**
"こんぶ" can be translated as "konbu" or "konnbu" (Both can be correctly reverse translated into "こんぶ").
Both has pros I think.
"konbu": It's shorter.
"konnbu": Translating rule is clear. Just "ん" is always translated into "nn"

**Comment by miurahr** [comment]
> Expected behavior
> こにゃく should be "konyaku"
> こんやく should be "konnyaku"
> こんにゃく should be "konnnyaku"

Does any standard or a common rule define it?

Kunrei-shiki ormanization is defined in [ISO 3602](https://www.iso.org/standard/9029.html) which does not defined as above.
https://en.wikipedia.org/wiki/Kunrei-shiki_romanization

One thing pykakasi violated is  a rule *Syllabic n (ん) is written as n' before vowels and y* so it would be better that
こんやく become "kon'yaku".

Hepburn-shiki romanization is defined in [MOFA](https://www.ezairyu.mofa.go.jp/passport/hebon.html)
にゃ become "NYA", んや become "NYA" from the definition,  so こんやく become "KONYAKU"

A difference between Hepburn-shiki and passport-shiki is usage of "※参考" table defined in MOFA.
MOFA defines  "※参考" for specially usage for passport.

pykakasiは、標準の定義や、法令などの公式な定義にもとづく実装をおこなっています。

>pykakasiが目指すところとして、
>「ローマ字への変換 」 = 「読みようによっては、元々のひらがなが推定出来る」というものであれば現在の仕様でも良いと思いましたが、
>「ローマ字への変換 」 = 「元々のひらがなが一意に決定出来る」というものであれば現在の仕様はバグと呼べるのかなと思いました。

このどちらでもありませんし、目指していません。

**Comment by shinbero** [comment]
-------  Comment in Japanese  -----------
すみません。pykakasiとKunreiやHepburn, Passport表記法について理解が足りておりませんでした。。。
ご紹介いただいたリンクを見ますと、確かにHepburn, Passport表記では現在の仕様のままでよく、
一方でISO 3602(Kunrei-shiki)では場合によって「ん」をn'と表記したり、「を」は「o」と表記すべきというところを理解しました。

公式にきちんと、「ん」の表記法が定義されているのを良く把握していなかったので、
個人的な観点で"目指すところ"があるのかなと考え、issueを切ってしまい申し訳ありませんでした。。
（また、今回の件で勉強になりました）

issue 110, 111を通してよりpykakasiが改善されるのを楽しみしております！



-------  Comment in English  -----------
I'm sorry. I didn't understand well about pykakasi, Kunrei-shiki, Hepburn romanization and passport romanization...
I looked at given link and understood that in Hepburn and Passport romanization, current pykakashi specification has no problem.
And I also understood that as you mentioned, in Kunrei-shiki, 「ん」 and 「を」 tranlation has room to improve.

Because I did't understand the translation rule for 「ん」 is exactly defined in official documentaion,
I had an personal opinion by myself and unexpectedly created issue...
I'm sorry about that again.
I could learn a lot through this issue. Thank you!

I'm looking forward pykakashi to be improved with issue 110 and  111!!
