### ISSUE TITLE
Problem with kanji + っ ?

### ISSUE THREAD

**Issue by elliotdl** [miurahr/pykakasi#114]
**Describe the bug**
I am both a beginner to japanese and python, so it is likely that I am making a mistake, but I may have found a bug

**Related issue**
None.

**To Reproduce**
```
import pykakasi
text= '思った 言ったら 行って'
kakasi = pykakasi.kakasi()
kakasi.setMode("H","a") # Hiragana to ascii, default: no conversion
kakasi.setMode("K","a") # Katakana to ascii, default: no conversion
kakasi.setMode("J","a") # Japanese to ascii, default: no conversion
kakasi.setMode("r","Hepburn") # default: use Hepburn Roman table
kakasi.setMode("s", True) # add space, default: no separator
kakasi.setMode("C", False) # capitalize, default: no capitalize
conv = kakasi.getConverter()
print(conv.do(text))
omotsu ta  itsutsu tara  itsu te
```

**Expected behavior**
` omotta ittara itte    `

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.8
 - pykakasi version: 2.0.4

**Test data(please attach in the report):**
None

**Additional context**
None

**Comment by miurahr** [comment]
There are several related entries in src/data/kakasidict.utf8 such as 
```
おもe 思
おもi 思
おもt 思
おもu 思
おもw 思
し 思
おもc 思
おもh 思
おもい 思い
おもいっきり 思いっきり
```
