### ISSUE TITLE
Infinite loop after running for a while

### ISSUE THREAD

**Issue by zyddnys** [miurahr/pykakasi#115]
**Describe the bug**
If I convert a lot of texts using pykakasi, the program freeze after a while.
I have found that the problem is caused by 
https://github.com/miurahr/pykakasi/blob/7d2179e7ec3fde9af2b5cb653c6475c819142c26/src/pykakasi/scripts.py#L152
Here if the if statement is not satisficed x will not increase and the while loop will not stop.
To reproduce
```python
kks = pykakasi.kakasi()
kks.convert('ﾞっ、')
```

**Comment by miurahr** [comment]
#118 try to handle the case.

What does 'ﾞっ、' should be converted in alphabet? 
@zyddnys any comment?
