### ISSUE TITLE
Hiragana for Number Counters

### ISSUE THREAD

**Issue by victorneo** [miurahr/pykakasi#116]
**Describe the bug**

My use case: I am using pykakasi to help generate Furigana from a given text or paragraph by using the Hiragana output.

Some counters, such as "十歳"  are converted as  `{"orig": "十", "hira": "じゅう"}, {"orig": "歳", "hira": "とし"}` instead of さい.

I am not sure if this is a bug with kakasi or whether there is a way for me to customise pykakasi to always convert 歳 -> さい if there are numbers before it.

**To Reproduce**

Use the input text: "ほかの十人は同じ施設の関係者で、六人は十歳未満の子どもでした。"

歳 is mapped as とし instead of さい。

**Environment (please complete the following information):**
 - OS: MacOS
 - Python 3.9.1
 - pykakasi version: 2.0.4

**Comment by miurahr** [comment]
pykakasi use dictionary search for converting words,
You can contribute to add new dictionary entry for the words. Please check `src/data/kakasidict.urg8`

**Comment by victorneo** [comment]
Thank you! I shall add the ages into the dictionary and open a PR.

Are you ok if I add the missing ages up to 100 and open a PR for it?

**Comment by miurahr** [comment]
@victorneo Dictionary based functions has always been welcome to contribute words, its vital!

**Comment by miurahr** [comment]
v2.0.6 out.
