### ISSUE TITLE
276 "kanji" are not converted

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [miurahr/pykakasi#119]
**Describe the bug**
First of all, thanks for having this project! Without Your work I could not do my project probably at all. 

The issue:
Some Japanese probably accidentally typed the same looking Chinese variant of kanji, or use simplified Chinese charcters mixed in, or some CJK unification conversion happened. 
The issue is: 見 and 見 are not the same in unicode. In the full list I've sent, some characters are clearly the simplified chinese versions of the kanji characters, however, these characters should be converted just the same I think.

**Related issue**
(if exist)

**To Reproduce**
(example)
I use the following code to convert Japanese text to romaji:

```
kakasi = pykakasi.kakasi()
kakasi.setMode("H", "a")  # Hiragana to ascii, default: no conversion
kakasi.setMode("K", "a")  # Katakana to ascii, default: no conversion
kakasi.setMode("J", "a")  # Japanese to ascii, default: no conversion
kakasi.setMode("r", "Hepburn")  # default: use Hepburn Roman table
kakasi.setMode("s", True)  # add space, default: no separator
kakasi.setMode("C", False)  # no capitalization
kakasi.getConverter().do(text)
text = "⽢⾃々〻ゞ业东丝丢两丨为丽么乐习书产亿们众优伙伟传伤你侧俱值內兰关兴兹军冻击别剧办动劳卖卡卢厉厌发变吗吧启呃员呜呢响哎哟唸啊啦喂喔嗎嗫嗯团场增处备头夺奶她妆妈妳姬实对寻尔带应废开张强怀态总恶战戾护报拋拥择损捥搔搞敌斩时晚暧极查标样欢步歲每污沟淚渴溫满灵热爱爸爹狱玛环现盘矿确离种竞笔类紧緖红约级纯纸线细终绊经结给绝续绮缔缚缠缲罗职胜脋脫舰艳蓝蔷薰虽蟬补见觉說计认让议记许讹诂诉词诛话该详语说诵请诺谁谈谍谛谢负贯贵贷费贽赶跃踠踩踬轨轮轻辉边达过运还这进远连选遗銮錬针钱铛银错镜镮长门闭问间闻阁队阳险隐难预领颗颜风飞饭马驶驾验骗骷髅髙鲜鸟鸠黑金北葉立切行見"
assert(kakasi.getConverter().do(text).replace(' ', '') == text) # it is true

```

**Expected behavior**
The characters converted to latin letters.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu Linux 18.04.01] macOS 10.13.6 (17G65)
 - Python [e.g. 3.6, pypy3.6.9-7.3.0] Python 3.7.4
 - pykakasi version: [e.g. v0.5b1, commit #123456 on master] 

**Test data(please attach in the report):**
A minimum test data to reproduce your problem.

**Additional context**

**Comment by miurahr** [comment]
You cannot convert Chinese standard kanji.

**Comment by BarnabasSzabolcs** [comment]
I have found some info on how to fix this issue:
https://stackoverflow.com/a/20843126/1031191

**Comment by BarnabasSzabolcs** [comment]
https://gist.githubusercontent.com/Answeror/8183907/raw/dc937755d9932fafe68d13692979e482fcacee60/kanji.json
And these characters appear within Japanese lyrics/subtitles. Let me show you an example:
笑えるくらい眩しい辉きで
Can you tell where's the hanzi?

So, I think it is worth to make your code more robust, or add a utility function.
Your algorithm can only benefit from this.
It is not my problem, I have fixed these cases for my code, and auto convert if users mix in hanzi by accindent or preference.
It was more like an FYI.

**Comment by BarnabasSzabolcs** [comment]
I think your converter should have raised an error at least.

**Comment by miurahr** [comment]
You may want to use Unihandecode that can handle Chinese.
https://github.com/miurahr/unihandecode
