### ISSUE TITLE
Deprecation of old api

### ISSUE THREAD

**Issue by miurahr** [miurahr/pykakasi#127]
**Is your feature request related to a problem? Please describe.**
Old API (v1.2 api) can be deprecated and removed in future release.

**Comment by miurahr** [comment]
v2.1.0 annotate deprecated for old API.
Users will see warning such as 
```DeprecationWarning: Call to deprecated method setMode. (Old API will be removed in v3.0.) -- Deprecated since version 2.1.```

**Comment by nagadomi** [comment]
Is it possible to implement the old API with the new API?
For example, how to convert kanji into hiragana and keep the katakana.
