### ISSUE TITLE
ver. 2.2.0: Unicode character "？" is mishandled.

### ISSUE THREAD

**Issue by theC0mptr0ll3R** [miurahr/pykakasi#145]
**Describe the bug**
When kakasi encounters "？" (Japanese question character), it turns buggy and reads one segment BEFORE the character "？" and appends the result right after it.

**Related issue**
N/A

**To Reproduce**
hoge@hoge hoge % python3
Python 3.9.5 (default, May  4 2021, 03:36:27)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
>>> from pykakasi import kakasi
>>> t1 = '見えますか。'
>>> t2 = '見えますか？'
>>> kks = kakasi()
>>> print(kks.convert(t1))
[{'orig': '見え', 'hira': 'みえ', 'kana': 'ミエ', 'hepburn': 'mie', 'kunrei': 'mie', 'passport': 'mie'}, {'orig': 'ますか。', 'hira': 'ますか。', 'kana': 'マスカ。', 'hepburn': 'masuka.', 'kunrei': 'masuka.', 'passport': 'masuka.'}]
>>> print(kks.convert(t2))
[{'orig': '見え', 'hira': 'みえ', 'kana': 'ミエ', 'hepburn': 'mie', 'kunrei': 'mie', 'passport': 'mie'}, {'orig': 'ますか', 'hira': 'ますか', 'kana': 'マスカ', 'hepburn': 'masuka', 'kunrei': 'masuka', 'passport': 'masuka'}, {'orig': '？', 'hira': '', 'kana': '', 'hepburn': '', 'kunrei': '', 'passport': ''}, {'orig': 'ますか', 'hira': 'ますか', 'kana': 'マスカ', 'hepburn': 'masuka', 'kunrei': 'masuka', 'passport': 'masuka'}]
>>>

**Expected behavior**
t2 should output 'みえますか？' instead of 'みえますかますか'.

**Environment (please complete the following information):**
 - OS: macOS 11.4 (20F71) Kernel Version: Darwin 20.5.0
 - Python 3.9.5
 - pykakasi version: 2.2.0 (updated via homebrew)

**Test data(please attach in the report):**
Please see above.

**Additional context**
N/A

**Comment by miurahr** [comment]
Do you report about "\uFF1F" ?
Are there any symbols to handle similar to "." (period)?

https://www.unicode.org/charts/PDF/UFF00.pdf

**Comment by theC0mptr0ll3R** [comment]
Hello sir,

I appreciate your reply!

"\uFF1F"... full-width question mark. Yes; that must be it.

For any other symbols and characters, I haven't encountered any oddities... yet ;o) But I'll be sure to point them out when I come across those, if any.

Thank you!! :o)

Best regards,
Oki
--
Media to People, Inc  <https://m2pi.net>
M: (+81) 80-4011-8128

**Comment by miurahr** [comment]
#146 handled your case. I've added "?" and also  ", " "." and "!" in Zenkaku character.

**Comment by theC0mptr0ll3R** [comment]
Thank you!! :o)))
