### ISSUE TITLE
How about romaji to kanji?

### ISSUE THREAD

**Issue by ymzlygw** [miurahr/pykakasi#148]
Hi, I want to know is there any way to convert romaji to kanji?

**Comment by miurahr** [comment]
Japanese kanji->romaji is one-way conversion. So reverse is not possible (there is no correct way).

For example,
`watashihaishaheitta.`

can be
`私は医者へ行った。`
`わたし歯医者へいった。`
....etc..

**Comment by ymzlygw** [comment]
> ishaheit

Yes, I got it , but what if I have cut the 'watashihaishaheitta' to 'wa ta shi ha isha he itta' before using tool like Mecab, is there anyway to convert it?

**Comment by miurahr** [comment]
Converting Romaji to kanji is known as Kana-Kanji conversion system and theorem, as you may know input method system.
You can try  google input tools on android, kotoeri on apple, or SKK on unix.

You may be interested it.
https://stackoverflow.com/questions/52532440/skk-for-kana-to-kanji-inverter

Unfortunately or fortunately, all of them are out of scope of pykakasi.

**Comment by ymzlygw** [comment]
> Converting Romaji to kanji is known as Kana-Kanji conversion system and theorem, as you may know input method system.
> You can try google input tools on android, kotoeri on apple, or SKK on unix.
> 
> You may be interested it.
> https://stackoverflow.com/questions/52532440/skk-for-kana-to-kanji-inverter
> 
> Unfortunately or fortunately, all of them are out of scope of pykakasi.

Thanks, I'll try it!

**Comment by miurahr** [comment]
Here web site demonstrate what you want using Google input API or mecab-skkserv
https://anti.rosx.net/etc/tools/rome.php
