### ISSUE TITLE
hepburnhira2.pickle is not found?

### ISSUE THREAD

**Issue by pacifictoy** [miurahr/pykakasi#15]
Hi,

I am trying to convert hiragana or kanji into romaji... was trying this:

> import pykasi
> j = pykasi.H2a()
Then I got this error:
IOError: [Errno 2] No such file or directory: '/Users/ronalds/.virtualenvs/testFlask/lib/python2.7/site-packages/pykakasi/hepburnhira2.pickle'

Do you know why I am missing those pickle file? 

Thanks for your help!

**Comment by miurahr** [comment]
Now in current master,  dictionaries are build when invoked by setup.py build.
It should be build when installing from source by `pip install` on Unix/Linux environment.
