### ISSUE TITLE
Instances of a kakasi() class are overlapped with _conv and _mode fields

### ISSUE THREAD

**Issue by hce-project** [miurahr/pykakasi#20]
Hi, i'm very happy to use a kakasi module in my current project HCE and applied Japanese projects, but have some notes. Most important is:
1) Because a _conv and _mode fields are defined outside of __init__ - they are overlapped in two or more instances of a classes. This gives some additional difficulties for case of usage of two or more instances of a converter for different purposes, for example for a split on tokens and convert to romaji...
If no any serious arguments, please move a definitions of all internal fields in to the __init__ to get classical instantiation.
Thanks.

**Comment by miurahr** [comment]
@hce-project  Could you test new version?

Thanks for propose.
