### ISSUE TITLE
Propose to have a structured return form from converter instead string with delimiters

### ISSUE THREAD

**Issue by hce-project** [miurahr/pykakasi#21]
Is it possible to have a possibility to make a structured form of conversion to romaji instead of a string result with delimiters? It is important because somebody (like me) can need to have a back hash of romaji and source (hiragana, kanji, etc sequences) but now after conversion it is impossible. It is will be very usable converter method or optional argument that lead to dict() will be returned instead of a string. Propose a key - source pattern and value - a converted.
Thanks!

**Comment by miurahr** [comment]
You may want to try MeCab for the purpose.
https://pypi.python.org/pypi/mecab-python3

**Comment by miurahr** [comment]
I'd like to start designing API and internal architecture for realizing structured result.
Because PyKakasi use very simple algorithm to analyze Japanese sentences, we should consider whole overhaul.

PyKakasi has a several component converting any to some. It may better connecting  pipelines of component in parallel then gathering end result and middle result into array of dictionary consist each words with original, kana, and roman.

**Comment by hce-project** [comment]
Many thanks for this decision because a structured response format is very easy to integrate and to use.
Also, now I using a mecab, but a problem is wrong detection of a parts of speech and person names.
Can You please to suggest me better tool especially for a POS tagging...
In a POS tagging I'm interesting especially in a nouns, verbs and person names detection.
Many thanks.

**Comment by miurahr** [comment]
https://github.com/miurahr/pykakasi/tree/topic-structured-return

**Comment by miurahr** [comment]
It seems now a point that it just works on topic branch.
There is not clean class structure and we may need to refactoring.

**Comment by miurahr** [comment]
@hce-project you can see a new interface as a test case here.
https://github.com/miurahr/pykakasi/blob/topic-structured-return/tests/test_pykakasi_structured.py

Cloud you give me a comment around API?

**Comment by miurahr** [comment]
New API released as v2.0.0a1
