### ISSUE TITLE
Conversion of Kanji lead to no characters on Python 2

### ISSUE THREAD

**Issue by 10000shiro** [miurahr/pykakasi#49]
Executing the sample code on the front page with Python 3 leads to the converted text:
`kana Kanji Majiri Bun `

Executing the sample code on the front page with Python 2 leads to the converted text:
`kana jiri`

No exception or warning is displayed. Is this intended behavior?

**Comment by miurahr** [comment]
This is fault of release process. I've just removed wheel binary package.
Because semidbm data file depends on Python versions, so database should be generated in install time.

**Comment by 10000shiro** [comment]
Was there a change from 0.90 to 0.91? Because I just changed to the 0.91 version via pip right now. Now it behaves as intended. Before, it did not work as intended with the pip realease.

Either way: thank you very much for the fix :)

**Comment by miurahr** [comment]
Thanks for feedback!
