### ISSUE TITLE
Issue with ー

### ISSUE THREAD

**Issue by kisuka** [miurahr/pykakasi#57]
I've had a few issues where words using the ー character have it converted into a hyphen rather than extending the previous character's sound.

For example:

デッデー is becoming dedde- instead of deddee.

**Comment by miurahr** [comment]
It is a specification in design. It is as same algorithm as original  kakasi v2.3.6 and original also convert it to dedde-.

**Comment by miurahr** [comment]
As same as #46 discussion, it is out of scope for kakasi simple algorithm to convert  ○, 々, and/or ー, based on a sentence context.

**Comment by miurahr** [comment]
C-kakasi convert it to ^ .  'デッデー' becomes 'dedde^ ' that is standard alternative way for' deddeê'
' deddee' is also a standard alternative way.

So it seems be a conversion bug.  It should become dedde^,  deddee or, deddeê
