### ISSUE TITLE
"ー" becomes "???" when ("K", "H" ) mode

### ISSUE THREAD

**Issue by taizan** [miurahr/pykakasi#59]
when I set kakasi.setMode("K","H")
and input "じゃーん" it returns "じゃ???ん"

**Comment by miurahr** [comment]
What it should be? Could you tell me an expected result?
There are several hyphen and similar marks in Unicode definition. 
It is better to see Unicode reference, such as follows,

- U+002D Hyphen
ー U+30FC Katakana-Hiragana Prolonged Sound Mark
‐ U+2010 Hyphen
‑ U+2011 Non-Breaking Hyphen
– U+2013
— U+2015
− U+2212
ｰ U+FF70

**Comment by miurahr** [comment]
Here ー in "じゃーん" seems to be a "ー U+30FC Katakana-Hiragana Prolonged Sound Mark" that is in a  "Katakana" table in Unicode standard, where  deal with k2.py range  
        ` (0x30a0 < ord(char[0]) and ord(char[0]) < 0x30fd)`

but convert logic for "H" is
```

            if self.isRegion(text[x]) and ord(text[x]) < 0x30f7:
                Hstr = Hstr + unichr(ord(text[x]) - self._diff)
                max_len = max_len + 1
            else: # pragma: no cover
                break
```
means 30f8-30fd is out of range.
