### ISSUE TITLE
市立 becomes イチリツ

### ISSUE THREAD

**Issue by noguxun** [miurahr/pykakasi#60]
text = "市立"
kakasi = kakasi()
kakasi.setMode('J', 'K')  
kakasi.setMode('H', 'K')
kakasi.setMode('K', 'K')
conv = kakasi.getConverter()
result = conv.do(text)  
print(result)

above code's  output is 
イチリツ

I am expecting
シリツ

**Comment by miurahr** [comment]
Thanks @noguxun for the report.
I've checked a dictionary and a result is 
```
kakasidict.utf8:いちりつ 市立
kakasidict.utf8:よこはまいちりつだい 横浜市立大
kakasidict.utf8:よこはましりつだい 横浜市立大
kakasidict.utf8:きょうといちりつげいだい 京都市立芸大
kakasidict.utf8:くまもとしりつ 熊本市立
kakasidict.utf8:しりつ 市立
kakasidict.utf8:いちりつふなばし 市立船橋
kakasidict.utf8:せんだいしりつ 仙台市立
kakasidict.utf8:ちばいちりつ 千葉市立
kakasidict.utf8:ちばいちりつこうこう 千葉市立高校
kakasidict.utf8:かわさきしりつ 川崎市立
kakasidict.utf8:まえばししりつ 前橋市立
kakasidict.utf8:おおさかいちりつだいがく 大阪市立大学
kakasidict.utf8:しりつとしょかん 市立図書館
kakasidict.utf8:しりつだい 市立大
```
Here I found both シリツ and イチリツ registered. It is correct as a dictionary because it has two pronunciations.

**Comment by noguxun** [comment]
Thanks for the explanation!
