### ISSUE TITLE
cannot convert character "々" with specific words.

### ISSUE THREAD

**Issue by shamoji101** [miurahr/pykakasi#66]
I found bugs with specific words when converting to Hiragana.

```
from pykakasi import kakasi

K = kakasi()
K.setMode("J","H")
conv = K.getConverter()
print(conv.do("月々"))
print(conv.do("毎月々"))
print(conv.do("佐々木"))
print(conv.do("中佐々木"))
print(conv.do("代々木"))
print(conv.do("次代々木"))
```
```
つきづき
まいつき々
ささき
ちゅうさ々き
よよぎ
じだい々き
```

**Comment by miurahr** [comment]
What is an expected result? If these has any expected result, we need to add it to dictionary. If not, I'd like to add logic to remove 々 because 々 only don't have specific pronounse/translitaration.

**Comment by shamoji101** [comment]
I expected this.
```
print(conv.do("毎月々")) 
#まいつきづき
print(conv.do("中佐々木"))
#なかささき
print(conv.do("次代々木"))
#つぎよよぎ
```

This issue's main purpose is bug reporting. Because I thought something wrong with pykakasi.
I don't care about fixing it or not. (I can ignore this issue.)

```
from pykakasi import kakasi,wakati

K = kakasi()
K.setMode("J","a")
conv = K.getConverter()
print(conv.do("月々"))
print(conv.do("毎月々"))
print(conv.do("佐々木"))
print(conv.do("中佐々木"))
print(conv.do("代々木"))
print(conv.do("次代々木"))
```
```
tsukizuki
maitsuki々
sasaki
chuusa々ki
yoyogi
jidai々ki
```
This output may not be a good answer. because convert mode is to ascii-code. 々 is not ascii-code.

**Comment by miurahr** [comment]
Thank you for information. I'd like to fix dictionary  and also fix logic not to output 々 in ascii-mode.
