### ISSUE TITLE
Issues on Katakana half-width

### ISSUE THREAD

**Issue by nil-vn** [miurahr/pykakasi#87]
![image](https://user-images.githubusercontent.com/5258659/66447510-7b34fc80-ea89-11e9-9d86-8d4d03bd7e97.png)
It's useful module to convert Japanese to Romaji.
But, I tested with Half-width Kana, and same like it could not convert to Romaji. Please tell me if it's not a issue.
Thank you so much.

**Comment by miurahr** [comment]
Half-width Katakana defined in Unicode standard was a legacy, which was deprecated in 1978 as JIS standard. It is exist  only for legacy data exchange.

PyKakasi is born in 21 century and won't support deprecated 20 century's chars.

There are  some utility to convert legacy data to current standard chars.

If there are good python library to do it and someone propose a patch, it is welcome.

**Comment by miurahr** [comment]
https://pypi.org/project/jaconv/  may be one we can use to it.

**Comment by miurahr** [comment]
Integrating jaconv into pykakasi would be great. We can add an option to preconvert with jaconv.
